django_learning/openchat/chat/urls.py
from django.urls import path


from . import views

app_name = 'chat'
urlpatterns = [
    path(
        '',
        views.login,
        name="login"
        ),
    path(
        'conversations',
        views.conversation_list,
        name='conversation_list'
        ),
    path(
        'conversations/create-conversation',
        views.create_conversation,
        name='create_conversation'
    ),
    path(
        'conversations/<conversation>',
        views.message_list,
        name='message_list'
        ),
    path(
        'signup',
        views.signup
    ),
]

django_learning/openchat/openchat/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('chat/', include('chat.urls')),
]

django_learning/openchat/chat/models.py
from django.db import models
from django.contrib.auth.models import User


class Conversation(models.Model):
    name = models.CharField(max_length=30, unique=True, default="Void")
    users = models.ManyToManyField(User)
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        to_field="username",
        related_name="author",
        )

    def __str__(self):
        return self.name


class Message(models.Model):
    text = models.CharField(max_length=999)
    date = models.DateTimeField(auto_now=True)
    conversation = models.ForeignKey(
        Conversation,
        on_delete=models.CASCADE,
        to_field="name"
        )

    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        to_field="username",
        )

    def __str__(self):
        if len(self.text) <= 20:
            return "\n{} // sent {}\n".format(
                self.text,
                self.date
                )

        return "\n{}... // sent {}\n".format(
            self.text[:20],
            self.date
            )

django_learning/openchat/chat/forms.py
from django import forms
from .models import Conversation


class ConversationForm(forms.ModelForm):
    class Meta:
        model = Conversation
        fields = ['name', 'users']

django_learning/openchat/chat/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib.auth import authenticate, login as do_login
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm


from .models import Message, Conversation
from .forms import ConversationForm


def conversation_list(request):
    if request.user.is_authenticated:
        conversations = Conversation.objects.filter(
            users=request.user
            )
        return render(
            request,
            'chat/conversation_list.html',
            {'conversations': conversations}
            )

    return HttpResponseRedirect('')


def message_list(request, conversation):
    messages = Message.objects.filter(conversation=conversation)
    return render(
        request,
        'chat/message_list.html',
        {'messages': messages, 'user': request.user},
        )


def login(request):

    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)

        form.is_valid()
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']

        user = authenticate(username=username, password=password)
        if user is not None:
            do_login(request, user)
            return HttpResponseRedirect('conversations')

    else:
        form = AuthenticationForm()

    return render(request, 'chat/login.html', {'form': form})


def signup(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            do_login(request, user)
            return HttpResponseRedirect('conversations')

    else:
        form = UserCreationForm()
    return render(request, 'chat/signup.html', {'form': form})


def create_conversation(request):
    if request.method == 'POST':
        form = ConversationForm(request.POST)
        if form.is_valid():
            new_conversation = Conversation.objects.create(
                name=form.cleaned_data['name'],
                author=request.user,
                )
            new_conversation.users.set(form.cleaned_data['users'])
            new_conversation.save()
            return HttpResponseRedirect(
                '{}'.format(new_conversation.name)
                )

    else:
        form = ConversationForm(request.POST)
    return render(request, 'chat/create_conversation.html', {'form': form})

django_learning/openchat/chat/templates/chat/conversation_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}

    <link rel="stylesheet" type="text/css" href="{% static 'chat/conversation_list.css' %}">
    <title>Conversations</title>
</head>
<body>
    <div class="list_of_conversations">
        {% if conversations %}
            <ul>
                {% for conversation in conversations %}
                <li><a href="{% url 'chat:message_list' conversation %}">{{ conversation.name }}</a></li>
                {% endfor %}
            </ul>
    </div>
    {% else %}
        <p>You haven't started any conversations yet!</p>
    {% endif%}
    <button type="button"><a href="conversations/create-conversation">Create Conversation</a></button>

</body>
</html>

django_learning/openchat/chat/templates/chat/create_conversation.html
<!DOCTYPE html>
<html>
<head>
    <title>Openchat</title>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/create_conversation.css' %}">
</head>
<body>
    <h2>Create conversation</h2>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <small>{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <input type="submit" class="button" value="Create">
    </form>
    
</body>
</html>

django_learning/openchat/chat/templates/chat/login.html
<!DOCTYPE html>
<html>
<head>
    <meta charset='utf-8'>
    <title>Openchat</title>

    <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Capriola' rel='stylesheet'>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/login.css' %}">
</head>
<body>
    <h1 class="Title">Openchat</h1>
    <form method="POST">
        {% csrf_token %}

        {{form.username.errors}}
        <label for="{{ form.username.id_for_label}}">Username</label><br>
        {{ form.username }}<br><br>

        {{form.password.errors}}
        <label for ="{{ form.password.id_for_label}}">Password</label><br>
        {{ form.password }}<br><br>
        
       
        <input type="submit" class="button" id="submit" value="Login">
        <button type="button" class="button"><a href="signup">Sign up</a></button>
    </form>
        
    
</body>
</html>

django_learning/openchat/chat/templates/chat/message_list.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
    <link rel='stylesheet' type='text/css' media='screen' href="{% static 'chat/message_list.css' %}">

    <title>Conversation</title>

</head>
<body>   
        {% if messages %}
            <ul class="message_list">
                {% for message in messages %}
                {% if message.author == user %}
            <div class="message-mine">
                <li>
                    <p class="message_text">{{message.text}}</p><p class="message_info">{{message.date}}, by {{message.author}}</p>                 
                </li>
            </div>

                    
                {% else %}
                <div class="message-other">
                <li>
                   <p class="message_text">{{message.text}}</p><p class="message_info">{{message.date}}, by {{message.author}}</p>
                </li>
               </div>
                {% endif %}
                {% endfor %}
            </ul>

    {% else %}
        <p class="no_messages">You haven't sent any messages yet!</p>
    {% endif%}
</body>
</html>

django_learning/openchat/chat/templates/chat/signup.html
<!DOCTYPE html>
<html>
<head>
    <title>Openchat</title>

    {% load static %}
    <link rel='stylesheet' type='text/css' href="{% static 'chat/signup.css' %}">
    <link href='https://fonts.googleapis.com/css?family=Calligraffitti' rel='stylesheet'>
    <link href='https://fonts.googleapis.com/css?family=Capriola' rel='stylesheet'>
</head>
<body>
    <div class="Title"><h1>Sign up</h1></div>
    <form method="POST">
        {% csrf_token %}
        {% for field in form %}
            <p>
                {{ field.label_tag }}<br>
                {{ field }}
                {% if field.help_text %}
                    <br><small>{{field.help_text}}</small>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </p>
        {% endfor %}
        <input type="submit" class="button" value="Sign up">
    </form>
    
</body>
</html>